### ISSUE TITLE
Choose Backend Technology

### ISSUE THREAD

**Issue by bwencke** [xternprojects/cultural-trail-backend#1]
Probably NodeJS

**Comment by ghost** [comment]
+1 for nodejs since it's the platform i'm familiar with

**Comment by deep-randhawa** [comment]
I am up for anything. I have experience with MySQL, not so much with
mongodb. So, mongodb will have some learning curve to it, but I am up for
it.

**Comment by anthonynatoli** [comment]
Node it is
