### ISSUE TITLE
Choose Hosting Service

### ISSUE THREAD

**Issue by bwencke** [xternprojects/cultural-trail-backend#2]
Preferably something free like Heroku. There shouldn't be too much traffic.

**Comment by ghost** [comment]
we can spin up machines on Digital ocean for cheap

**Comment by anthonynatoli** [comment]
I take it we want to keep this free? Or does the Cultural Trail have a budget allocated for this?
@bwencke

**Comment by ghost** [comment]
I have no idea of the requirements nor budget that the cultural trail has :/

**Comment by deep-randhawa** [comment]
We can host on Amazon web services, it should be pretty cheap , I'd say
10-20$ per annum. We guys should meet up and plan the design of the server,
and get to it.

**Comment by bwencke** [comment]
I haven't actually met with them yet, so I don't know if they have a budget for this or not. Odds are they expect it to be free. If they aren't willing to pay, WE definitely aren't going to. Since there won't be much traffic, free options include Heroku and Google App Engine, among others. I would give preference to Heroku over App Engine just because it is lighter and Heroku apps can be easily ported to other hosting services.

**Comment by ghost** [comment]
if we're going to use heroku, then we're going to commit ourselves to using postgres for storage which is fine with me

**Comment by anthonynatoli** [comment]
Heroku FTW
